- name: enable permissive SElinux
  ansible.posix.selinux:
    state: permissive
    policy: targeted
  notify:
    - restart_selinux
- name: open custom ports FirewallD
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: true
    zone: public
  with_items:
  - 5601
  - 5044
  - 9200
  notify: restart_firewalld
