    - name: copy elasticsearch
      copy:
        src: elasticsearch-8.11.1-x86_64.rpm
        dest: /home/kounne/elasticsearch-8.11.1-x86_64.rpm
        owner: root
        group: root
        mode: 0644
    - name: install elasticsearch
      ansible.builtin.yum:
        name: 
        - /home/kounne/elasticsearch-8.11.1-x86_64.rpm
        state: present
    - name: generate configuration for elasticsearch
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: 0660
    - name: reload systemd configuration
      systemd:
        daemon_reload: true
    - name: start elasticsearch service
      service: 
        name: elasticsearch
        state: started
        enabled: yes
    - name: setup password for elasticsearch
      shell:
        cmd: echo {{ elasticsearch_password }} | /usr/share/elasticsearch/bin/elasticsearch-reset-password -i -u elastic
    - name: is cluster alive?
      uri:
        url: "http://{{ host_IP }}:9200/_cluster/health"
        user: "{{ elasticsearch_login }}"
        password: "{{ elasticsearch_password }}"
      register: result
      retries: 5
      delay: 60

