    - name: copy elasticsearch
      copy:
        src: elasticsearch-8.11.1-x86_64.rpm
        dest: /home/kounne/elasticsearch-8.11.1-x86_64.rpm
        owner: root
        group: root
        mode: 0644
    - name: install elasticsearch
      ansible.builtin.yum:
        name: 
        - /home/kounne/elasticsearch-8.11.1-x86_64.rpm
        state: present
    - name: generate configuration for elasticsearch
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
    - name: start elasticsearch
      service:
        name: elasticsearch
        state: restarted
